version: '3.7'
services:
  zookeeper:
    image: wurstmeister/zookeeper

  kafka:
    image: wurstmeister/kafka
    ports:
    - "9092:9092"
    environment:
      #KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092
      #KAFKA_ADVERTISED_HOST_NAME: "kafka"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
    depends_on:
    - zookeeper

  postgresql:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
    volumes:
    - /var/postgresql/data:/var/lib/postgresql/data
    ports:
    - "5432:5432"

  pgadmin4:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "postgres@bv.com"
      PGADMIN_DEFAULT_PASSWORD: "postgres"
    ports:
    - "9990:80"
    depends_on:
    - postgresql

#  local-s3:
#    image: localstack/localstack
#    environment:
#      SERVICES: "s3"
#      DEFAULT_REGION: "eu-central-1"
#      DATA_DIR: "/tmp/localstack/data"
#      HOSTNAME: local-s3
#    ports:
#    - "4566:4566"
#    - "9999:8080"
#    volumes:
#    - localstack-data:/tmp/localstack

  bv:
    build: .
    ports:
    - "${PORT}:8080"
    environment:
      JDBC_URL: "jdbc:postgresql://postgresql:5432/postgres"
      JDBC_USER: "postgres"
      JDBC_PASSWORD: "postgres"
      JDBC_DRIVER: "org.postgresql.Driver"
      KAFKA_HOST: "kafka"
#      S3_ENDPOINT: "http://local-s3:4566"
    depends_on:
    - postgresql
    - kafka
#    - local-s3

volumes:
  localstack-data:
    name: localstack-data
